### ISSUE TITLE
ActiveRecord::RecordNotFound (Couldn't find FullTextSearch::TagType with 'id'=0)

### ISSUE THREAD

**Issue by Stag0006** [clear-code/redmine_full_text_search#101]
プラグインインストール後、空のDBでチケットを作成し、txt、Excelファイルを添付。
添付ファイルのタイトル、ファイル内のワード、NULLで検索すると下記エラーとなります。
検索オプションで添付ファイルを除外した場合はエラーなく、結果が返ってきます。
解決策について、ご教示いただけますでしょうか。

<pre>
Started GET "/redmine/projects/joukan/search?utf8=%E2%9C%93&scope=&q=test" for 127.0.0.1 at 2021-11-05 14:01:40 +0900
Processing by SearchController#index as HTML
  Parameters: {"utf8"=>"✓", "scope"=>"", "q"=>"test", "id"=>"joukan"}
  Current user: user (id=1)
[full-text-search][search] {"search_id":"1636088500.2305398","q":"test","scope":"","all_words":"1","titles_only":"0","attachments":"1","open_issues":"0","offset":0,"limit":10,"order_target":"score","order_type":"desc","options":"0","issues":"1","news":"1","documents":"1","changesets":"1","wiki_pages":"1","messages":"1","changes":"1","tags":[],"user_id":1,"project_id":1,"n_hits":1,"total_n_hits":1,"elapsed_time":0.007348775863647461,"timestamp":"2021-11-05T05:01:40Z"}
  Rendering plugins/redmine_full_text_search/app/views/search/index.html.erb within layouts/base
  Rendered plugins/redmine_full_text_search/app/views/search/index.html.erb within layouts/base (25.4ms)
Completed 500 Internal Server Error in 71ms (ActiveRecord: 26.7ms)
  
ActiveRecord::RecordNotFound (Couldn't find FullTextSearch::TagType with 'id'=0):
  
plugins/redmine_full_text_search/lib/full_text_search/searcher.rb:375:in `block in tag_drilldowns'
plugins/redmine_full_text_search/lib/full_text_search/searcher.rb:374:in `each'
plugins/redmine_full_text_search/lib/full_text_search/searcher.rb:374:in `collect'
plugins/redmine_full_text_search/lib/full_text_search/searcher.rb:374:in `tag_drilldowns'
plugins/redmine_full_text_search/app/views/search/index.html.erb:128:in `_plugins_redmine_full_text_search_app_views_search_index_html_erb__272185543_886515463000'
lib/redmine/sudo_mode.rb:61:in `sudo_mode'
</pre>

・環境
OS：Windows10 64bit
bitnami Redmine version：4.2.2.stable
Ruby version：2.6.8
Rails version ：5.2.6
Mroonga：11.06
MariaDB：10.2.40
full_text_search ：1.0.4
chupa-text-http-server-1.0.6

**Comment by kou** [comment]
この問題が発生する添付ファイルを提供してもらえませんか？

**Comment by Stag0006** [comment]
対象のファイルになります。
[test.txt](https://github.com/clear-code/redmine_full_text_search/files/7489373/test.txt)
[新規 Microsoft Office Excel ワークシート.xlsx](https://github.com/clear-code/redmine_full_text_search/files/7489377/Microsoft.Office.Excel.xlsx)

**Comment by kou** [comment]
ありがとうございます。
このプラグインのバグだったので修正しました。
