### ISSUE TITLE
fts_targets records of custom field is not deleted when Issue is deleted

### ISSUE THREAD

**Issue by tkark** [clear-code/redmine_full_text_search#105]
There is an issue where the fts_Targets record in the custom field is not deleted when an Issue is deleted.
An error occurs when data entered in a custom field is included in the search keywords.

Steps to Reproduce
1. Register a ticket with custom fields
2. Delete the registered ticket
3. Search keywords in the custom field.

Confirmed with Redmine 4.2.5 and master as of 8/10/2022.
This is occurring from an earlier version of FTS.

【日本語】
Issueを削除したときにカスタムフィールドのfts_targetsのレコードが削除されない事象が発生しています。
このため、カスタムフィールドに登録されていたデータに検索時のキーワードが含まれていると、RecordNotFoundが発生します。
ユーザーからはPage Not Found(HTTP 404)が見えます。

以下の手順で再現可能です。
1.カスタムフィールドのあるチケットを登録する
2.登録したチケットを削除する
3.カスタムフィールドに登録していた文言をキーワードとしてFTSで検索する

**Comment by kou** [comment]
Thanks. I could reproduce this and have been fixed.

**Comment by tkark** [comment]
Thank you very much for your prompt response.
I have confirmed that the problem has been resolved in my environment.
