### ISSUE TITLE
削除したカスタムフィールドの単語を検索時、エラー

### ISSUE THREAD

**Issue by Stag0007** [clear-code/redmine_full_text_search#108]
1.カスタムフィールド（リスト形式）を登録し、チケットにて値を選択。
2.カスタムフィールドごと削除した際
3.値にしていた単語を検索→下記エラーとなります。
Page not found
The page you were trying to access doesn't exist or has been removed.

production.logよりエラー内容。
ActiveRecord::RecordNotFound (Couldn't find CustomValue with 'id'=1476):

custom_valueにて記載IDが削除されていることを確認。
カスタムフィールド削除時、設定されていた値の検索でエラーとならないよう、
ご対応いただくことは可能でしょうか。
（カスタムフィールドを削除する際に気を付けていればよかったのですが。。。）

プラグインのバージョン：1.0.4

**Comment by komainu8** [comment]
手元で問題を再現させたいので、下記の情報をいただけますか？

* Redmineのバージョン
* Rubyのバージョン
* Ruby on Railsのバージョン
* MySQL(MariaDB) or PostgreSQL のバージョン
* Mroonga or PGroonga のバージョン

**Comment by HashidaTKS** [comment]
手元でも再現することが確認できました。
一旦再現環境の情報を頂かなくても大丈夫そうです！

**Comment by Stag0007** [comment]
ありがとうございます。
念のため、当環境をお伝えしておきます。
よろしくお願いいたします。
・Redmine：4.2.2
・Ruby：2.6.8
・Ruby on Rails：5.2.6
・MariaDB：10.2
・Mroonga：11.0.6

**Comment by kou** [comment]
対応しました。
ゴミレコードは`RAILS_ENV=production bin/rails full_text_search:synchronize`で消えるのでそれを実行すれば検索時のエラーもなくなるはずです。

**Comment by Stag0007** [comment]
検索時にエラー発生しないことが確認できました。
対応ありがとうございます。
