### ISSUE TITLE
Thinking of OpenAI

### ISSUE THREAD

**Issue by uhuntu** [clear-code/redmine_full_text_search#113]
Hello there, nice to meet you guys.

I am excited to try your plugins, but actually I would like to integrate OpenAI Embeddings into Redmine to polish its search.

As known, Embeddings are some vectors, it will working well with Vector Database. As known, MySQL or PostgreSQL are NOT Vector Database. Redis or Milvus are Vector Database. But actually I am wondering if Groonga that with MySQL or PostgreSQL can act as something like Vector Database ?

I am not the Groonga expert like yours, so please think about the issues. Thanks.

==

PS. When I was trying your plugin, that increased my DB significantly. My ideas is something like Xapian solutions ?

**Comment by kou** [comment]
Groonga can work with embedding documents if the embeddings are sparse.

Mroonga/PGroonga integrations for the feature aren't implemented yet.
