### ISSUE TITLE
Support synonym

### ISSUE THREAD

**Issue by kou** [clear-code/redmine_full_text_search#27]
Groongaには[同義語展開](http://groonga.org/ja/docs/reference/commands/select.html#select-query-expander)という機能があり、入力されたクエリーを拡張して検索できます。たとえば、「ドリルダウン」で検索したら自動で「ドリルダウン OR drilldown」で検索するみたいな感じです。

MroongaとPGroongaにはこれらの機能を作る機能はまだないんですが、MroongaとPGroongaで使えるようになったらこのプラグインでも使えるようになるとうれしいです。使えるようになる、というのは、登録されている同義語を使う機能があるということと同義語管理UIがあるということです。

同義語はRedmineに入っているデータから学習して半自動で整備できるようになるとウハウハだなぁと思っています。

**Comment by kou** [comment]
「打ち合わせ」で「打合せ」もヒットする、みたいなのも同義語展開で実現できます。

**Comment by okkez** [comment]
v0.5.0 で Groonga を叩くようになったから、実装しようと思えばできる？

**Comment by kou** [comment]
Implemented.
