### ISSUE TITLE
pgroonga is slower than mroonga???

### ISSUE THREAD

**Issue by okkez** [clear-code/redmine_full_text_search#33]
#30, #31 に対応してから明らかに性能差が出ている。
pgroonga の方でも何かすれば同等の速度になるはず。

mroongaで初回100ms以下のクエリがpgroongaでは250ms-500ms程度になってしまう。

**Comment by okkez** [comment]
v0.6.2時点でのベンチマーク結果
http://www.clear-code.com/blog/2017/9/25.html

**Comment by kou** [comment]
Maybe outdated.
Schema is rewritten.
