### ISSUE TITLE
Internal server error occurs when full text search

### ISSUE THREAD

**Issue by okkez** [clear-code/redmine_full_text_search#53]
何らかの原因で searcher_records に journals に存在しない レコードを指すレコードが残っていた場合、全文検索を実行するとサーバーエラーになることがある。

ログを確認すると mecab のエラーで issue_contents にレコードが作成できていない様子だった。
これは、あるチケットに追加するコメントが増えると発生する可能性がある。
手元で確認した感じでは約1.8MBで発生した。

しかし、チケットに長いコメントを追加してmecabのエラーを発生させても、searcher_recordsにゴミレコードは残らない。

**Comment by kou** [comment]
Maybe outdated.
Schema is rewritten.
