### ISSUE TITLE
Not want to be installed if name <> "full_text_search" !!!

### ISSUE THREAD

**Issue by bizlevel** [clear-code/redmine_full_text_search#58]
In plugin directory a lot plugins name begins with redmine.
And if i have 20 plugins in this way, i want install next plugin with same name rule.
But DB migrate not work if name of this plugin is not equal to full_text_search!!

**Comment by kou** [comment]
Can you show how to reproduce this case?

**Comment by bizlevel** [comment]
just rename folder, and try use rake:db:migrate:plusins - if i correctly ect remember this command.

**Comment by kou** [comment]
Thanks.
I've fixed it.
