### ISSUE TITLE
 Synchronization task fails if SJIS encoded text is included in the attachment.

### ISSUE THREAD

**Issue by okojoalg** [clear-code/redmine_full_text_search#63]
I will like to announce a problem.
The synchronization task fails.
Perhaps it is since Shift JIS encoded text is included in the attached file.

**Comment by kou** [comment]
Could you provide a sample attachment file that can reproduce your problem?

**Comment by kou** [comment]
No feedback.
I think that this has been fixed at master.

**Comment by okojoalg** [comment]
I'm sorry. I forgot.
The data where the phenomenon occurred can not be passed because of customer information.
I will apply master from now on.
