### ISSUE TITLE
Search result date is incorrect.

### ISSUE THREAD

**Issue by okojoalg** [clear-code/redmine_full_text_search#65]
If you execute the synchronize task after applying this plugin, the following problems occur.
In the case of CustomValue, fixed value '1970-01-01 00:00:00' are entered in searcher_records.original_created_on and searcher_records.original_updated_on. 
So '1970-01-01 00:00:00' is displayed on the search result screen.
Can not be the original issue datetime?

**Comment by kou** [comment]
It will be fixed at the master.
