### ISSUE TITLE
translation missing: ja.label_full_text_search_result_order

### ISSUE THREAD

**Issue by ryouma-nagare** [clear-code/redmine_full_text_search#68]
### 環境情報
- OS：CentOS7.6
- Redmine： 4.0.4.stable.18325
- redmine_full_text_search：commit 3b0a880cf31b78d737eea37efe6ac7ae8107b2e2
- groonga：9.0.4
- PGroonga：2.2.0
- Ruby：2.5.5-p157 (2019-03-15) [x86_64-linux]
- Rails：5.2.3
- AppServer：unicorn 5.4.1
- PostgreSQL：11.4

ja.yml / en.yml から `label_full_text_search_result_order` が削除されましたが、
index.html.erb に `<legend><%= l(:label_full_text_search_result_order) %></legend>`  があるため、ラベルが変換されなくなってしまいました。

**Comment by kou** [comment]
おぉ。。。
戻しておきました。
