### ISSUE TITLE
 The number of "All" will be the number of selected tabs when switching tabs.

### ISSUE THREAD

**Issue by ryouma-nagare** [clear-code/redmine_full_text_search#69]
### 環境情報
- OS：CentOS7.6
- Redmine： 4.0.4.stable.18325
- redmine_full_text_search：commit 3b0a880cf31b78d737eea37efe6ac7ae8107b2e2
- groonga：9.0.4
- PGroonga：2.2.0
- Ruby：2.5.5-p157 (2019-03-15) [x86_64-linux]
- Rails：5.2.3
- AppServer：unicorn 5.4.1
- PostgreSQL：11.4

検索後、「すべて」から別なタブに移動すると、「該当のタブの件数＝すべて」となります。

![image](https://user-images.githubusercontent.com/12542118/60867582-2acdb900-a266-11e9-8b2c-40a5550b6876.png)

**Comment by kou** [comment]
この数ヶ月のうちにいい感じにする予定です！

**Comment by ryouma-nagare** [comment]
楽しみにしています

**Comment by kou** [comment]
実装しました。
ただ、そろそろリリースされるGroonga 9.0.5にアップグレードするまでは治らないので注意してください。

**Comment by ryouma-nagare** [comment]
groongaのアップグレード後、解決していることを確認しました。
ありがとうございました！

**Comment by ryouma-nagare** [comment]
確認後、yum update と redmine_full_text_search のgit pullをしたところ、再発するようになってしまいました。

- groonga-libs-9.0.6-1.el7.x86_64
- redmine_full_text_search：commit 798971b

**Comment by kou** [comment]
ページネーションで問題が見つかり #70 Groongaにも問題があったので次のGroongaのリリースまでは従来どおりの挙動に戻すようにしました。今月末リリースのGroonga 9.0.7にアップグレードすればまた動くようになります。

**Comment by ryouma-nagare** [comment]
了解しました。
