### ISSUE TITLE
Paging is not working

### ISSUE THREAD

**Issue by a9zawa** [clear-code/redmine_full_text_search#70]
検索結果ページのページングが機能していないようです。
11件以上ヒットした場合でも、ページ下部にページングのリンクが表示されず、「(1-10/10)」と表示されてしまいます。

環境情報
* OS: ubuntu 18.04
* Redmine: 4.0.4.stable
* Ruby: 2.6.3-p62
* Rails: 5.2.3
* APServer: Unicorn 5.5.1
* DB: PostgreSQL 10
* redmine_full_text_search: commit 34819f02c51984842bcfee652efa1bb62af125fe
* postgresql-10-pgroonga: 2.2.1-2~ubuntu18.04.1
* libgroonga0: 9.0.6-2~ubuntu18.04.1

---

https://github.com/clear-code/redmine_full_text_search/commit/8416db40a8f56a87a9d50d7f5b69c0a898ae4882
こちらの修正ですが、以下 @result_set.count の修正も必要かと思います。
https://github.com/clear-code/redmine_full_text_search/blob/8416db40a8f56a87a9d50d7f5b69c0a898ae4882/lib/full_text_search/hooks/controller_search_index.rb#L39

試しに手元の環境で @result_set.n_hits に修正したところページング部が表示されるようになりました。
ただし、2ページ目以降に遷移した場合検索結果が表示されませんでした。
デバッグ用にソース一部修正して動作確認したところ、slice に対しての limit と offset の処理順が逆になっているような動作をしているように思います。
十分にヒットするクエリでも、limit = 10, offset = 20 の場合検索結果0件になりました。また、limit = 10, offset = 5 の場合検索結果は5件になりました。
上記よりlimit分に絞った後offset分開始位置を進めている動きになっていると推測しております。

以上ご参考までに。

**Comment by kou** [comment]
たしかにその通りですね！
直しました！

`offset`と`limit`の方はGroongaの問題だったのでそっちで直しました。
