### ISSUE TITLE
Search results differ between top level and project level

### ISSUE THREAD

**Issue by sugi-t** [clear-code/redmine_full_text_search#80]
Thank you for valuable plugins. After #79 fix applied, other issue has been identified.

Issue description:
Projects are defined as following and the same file1 attached to sub projects:
 Project1 (parent)
   Project1-1 (child of Project1)    test file1 attached to this project
   Project1-2 (child of Project1)    test file1 attached to this project

If search requested from Project1 level, the results are as estimated (file1 hits for each sub project).
If search requested form top level (without project selection), the results are also as estimated (file1 hits for each sub project).
If search requested form Project1-1 or Project1-2 level, no hits for the same search word.
(File1 attached to a ticket in Project1-1 is searched fine both from parent levels and the sub project level.)

Could you please confirm the issue?

![image](https://user-images.githubusercontent.com/60026045/73618612-2aff2d00-466c-11ea-85bc-ecae93f49771.png)

**Comment by kou** [comment]
Thanks for your report.
I've fixed it. But drilldown count isn't consistent... "All" count doesn't equal to sum of other drilldown counts...

**Comment by sugi-t** [comment]
Thank you for your kind attention and my apologize for taking some time for response.
I confirmed the issue has been fixed.
