### ISSUE TITLE
Unnecessary parameters are added to the URL when transitioning from the search result

### ISSUE THREAD

**Issue by a9zawa** [clear-code/redmine_full_text_search#86]
検索結果からチケット等に遷移した際に、search_id, search_n のURLパラメータが付与された状態でチケット画面が表示されます。
検索結果のリンクに上記パラメータを付与しているのは以下の部分かと思います。
https://github.com/clear-code/redmine_full_text_search/blob/master/app/views/search/index.html.erb#L173-L174

こちら画面遷移の上で必要があっての仕様でしょうか。

検索して探し当てたチケットのURLをコピーしてRedmine外で共有するなどの際に、不要なURLパラメータを削る必要があるため、チケットを表示した際にはURLパラメータがなにもついていない状態であってほしいという要望です。

**Comment by kou** [comment]
画面遷移の上では必要ありません。

検索精度のチューニングのために必要です。この情報を使ってユーザーに提供した検索結果が本当にユーザーが必要としていたものだったかを統計的に解析して検索結果のチューニングに利用します。

無効にするとしたらオプションでオフにできるようにします（が、あんまり私が優先的に時間を使って作業したい改良ではありません）。

**Comment by kou** [comment]
プラグインの設定画面で「トラッキングを有効化」を「無効」にできるようになりました。
