### ISSUE TITLE
Syntax error query causes 500 server error

### ISSUE THREAD

**Issue by petemcdonnell** [clear-code/redmine_full_text_search#91]
Brackets (parenthesis) in the search term aren't properly handled?

Resulted in a 500 sever error...

From the redmine log:

`Started GET "/projects/customers/search?utf8=%E2%9C%93&q=%28my+search+term&button=&scope=&titles_only=0&open_issues=0&attachments=1&order_target=score&order_type=desc&options=0&search_id=1593002991.1595986&issues=1" for my.ip.address.here at 2020-06-22 09:51:22 -0100
Processing by SearchController#index as HTML
  Parameters: {"utf8"=>"✓", "q"=>"(my search term", "button"=>"", "scope"=>"", "titles_only"=>"0", "open_issues"=>"0", "attachments"=>"1", "order_target"=>"score", "order_type"=>"desc", "options"=>"0", "search_id"=>"1593002991.1595986", "issues"=>"1", "id"=>"customers"}
  Current user: my.user (id=77)
Completed 500 Internal Server Error in 24ms (ActiveRecord: 9.9ms)`

`ActiveRecord::StatementInvalid (Mysql2::Error: failed to parse fulltext search keyword: <(my search term>: <Syntax error: <(my search term||>>: SELECT `fts_tags`.`id` FROM `fts_tags` WHERE `fts_tags`.`type_id` = 1 AND (MATCH (`name`) AGAINST ('(my search term' IN BOOLEAN MODE))):
`

**Comment by kou** [comment]
Thanks for your report.
I've fixed this.
