### ISSUE TITLE
How to search the text of an attachment that already exists?

### ISSUE THREAD

**Issue by ioio000** [clear-code/redmine_full_text_search#92]
I installed full_text_search and performed a data sync, but the text in existing attachments (docx, xlsx...etc) is not searched.
When I newly attach the same file, the text in that file is searchable.

`bundle exec rake redmine:plugins:migrate RAILS_ENV=production`
Need other commands?

Environment:
bitnami-redmine-4.1.1-2-windows-x64
mariadb-10.4.8-with-mroonga-9.09-winx64
full_text_search 1.0.3

**Comment by kou** [comment]
You need to run the `full_text_search:synchronize` task: https://github.com/clear-code/redmine_full_text_search#synchronize-data

**Comment by ioio000** [comment]
I missed writing commands.
`bundle exec rake full_text_search:synchronize RAILS_ENV=production`

After syncing I can search for tickets and wiki strings.
It was not possible to search the text of an attachment that already exists.

**Comment by kou** [comment]
Could you attach `log/production.log` while you run `full_text_search:synchronize`?

**Comment by ioio000** [comment]
I tried it in a test environment.
Please check the log attached.
The xlsx file was able to be searched.
[command.log](https://github.com/clear-code/redmine_full_text_search/files/4879196/command.log)
[production.log](https://github.com/clear-code/redmine_full_text_search/files/4879085/production.log)

Search results after synchronization
<img width="337" alt="1" src="https://user-images.githubusercontent.com/67868043/86597006-1d145600-bfd6-11ea-90c3-087b277e6ba7.png">

User document has "test.docx" file but it is not searched.
<img width="278" alt="2" src="https://user-images.githubusercontent.com/67868043/86597130-4634e680-bfd6-11ea-937d-b5d43f345773.png">

The same "test.docx" file as "test (1).docx" was added.
<img width="270" alt="3" src="https://user-images.githubusercontent.com/67868043/86597541-da06b280-bfd6-11ea-8682-c582ed975a27.png">

I can find the search string in the "test (1).docx" file.
<img width="290" alt="4" src="https://user-images.githubusercontent.com/67868043/86597632-f571bd80-bfd6-11ea-934b-e2cfe7128291.png">

**Comment by kou** [comment]
Thanks.
I've fixed it.

Could you upgrade to the master and re-run `full_text_search:synchronize`?

**Comment by ioio000** [comment]
ok.
It works.
Thanks.
