### ISSUE TITLE
NoMethodError&Child already added

### ISSUE THREAD

**Issue by naoki7090624** [clear-code/redmine_full_text_search#94]
Hello, I try to install this plugin to my redmine as following command.
```
$ cd /var/redmine/
$ git clone https://github.com/clear-code/redmine_full_text_search.git plugins/full_text_search
$ bundle install
$ bundle exec rake redmine:plugins:migrate RAILS_ENV=production
$ bundle exec rake full_text_search:synchronize RAILS_ENV=production
```

but, I got this error.

```
rake aborted!
Child already added
/var/redmine-3.4.6ib/redmine/menu_manager.rb:370:in `add_at'
/var/redmine-3.4.6/lib/redmine/menu_manager.rb:387:in `add'
/var/redmine-3.4.6/lib/redmine/menu_manager.rb:305:in `push'
...
```

Also, I found the NoMethodError in my error log.
```
full_text_search/app/jobs/full_text_search/extract_text_job.rb:4:in `<class:ExtractTextJob>': undefined method queue_with_priority' for FullTextSearch::ExtractTextJob:Class (NoMethodError)
```
I have changed the some files on db/migrate/ as `ActiveRecord::Migration[5.2]` to `ActiveRecord::Migration[4.2]` to solve the migration error due to rails version.

Could you give me any solution?

There are about my environment.
* rails: 4.2
* redmine: 3.4.6
* MySQL: 5.7.31
* Groonga: 10.0.5
* Mroonga: 10.05

**Comment by komainu8** [comment]
The latest version of this plugin doesn't support for Redmine 3.x.
We suggest that we use Redmine 4.x. Because Redmine 3.x had finished support. (Ref: https://www.redmine.org/news/128)

The following issue will probably be also useful for the solution to this problem. 
https://github.com/clear-code/redmine_full_text_search/issues/85#issuecomment-617525126

**Comment by naoki7090624** [comment]
Thank you for advice.

Yes, it's similar situation to the issue #85. With reference to the issue, I will try using the old version first.

Thank you for giving solution.
